### ISSUE TITLE
Force reload for development?

### ISSUE THREAD

**Issue by jsieber** [stevewithington/MuraPlugin#1]
Hi Steve,
Is there a way to force a reload of the plugin on each request during development, so that Mura does not need to be reloaded for each change to the eventHandler.cfc. Something similar to the config setting in the FW/1 plugins?
Thanks,
John

**Comment by stevewithington** [comment]
@jsieber-aca,

I've added a new setting (https://github.com/stevewithington/MuraPlugin/blob/65e5db18e9acc9788d295dfbf20e23a716f3de6c/plugin/settings.cfm#L19) that allows you to tell the plugin to reload on each request in the latest version.

Cheers,
Steve

**Comment by jsieber** [comment]
@stevewithington Fantastic! Thanks so much for all of your fantastic Mura work.

**Comment by stevewithington** [comment]
@jsieber-aca hold on ... i just noticed an issue. i'll get it fixed shortly.

**Comment by stevewithington** [comment]
@jsieber-aca, ok ... should be working now.

**Comment by jsieber** [comment]
@stevewithington thanks again!
